### ISSUE TITLE
error......

### ISSUE THREAD

**Issue by LeePC** [FelixFourcolor/noteblock-generator#1]
cmd command : noteblock-generator masule.nbs mine -l 0 10 0 -d overworld -t stone

ERROR: unrecognized music format for 'masule.nbs'
UnicodeDecodeError: 'cp949' codec can't decode byte 0xfc in position 4: illegal multibyte sequence

**Comment by FelixFourcolor** [comment]
I assume `mascule.nbs` is a Note Block Studio file? My program does not work with and is not in anyway related to NBS. Instead it reads music source code in my own defined format. You can see examples of such source code in any of my published projects, such as https://github.com/FelixFourcolor/Herr-unser-Herrscher.

For the foreseeable future I only intend this program for my own use, so there will not be any documentation for writing the music source code. You are of course welcome to study the source code of this program or of my published projects to reverse engineer it. :slightly_smiling_face:
